# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('characteristic', models.TextField()),
                ('image', models.ImageField(upload_to='characters')),
                ('turn_priority', models.IntegerField()),
                ('character_priority', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
