# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='turn_priority',
            new_name='turn_order',
        ),
    ]
