# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0006_auto_20160805_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.Game')),
            ],
        ),
    ]
