# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game',
            new_name='current_game',
        ),
    ]
