# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20160805_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_game',
            new_name='last_played_game',
        ),
    ]
