# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160805_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='ip',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
