# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160805_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=6),
        ),
    ]
