# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20160804_0127'),
        ('player', '0003_auto_20160805_1517'),
        ('game', '0007_game_max_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersRoleInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_role_in_game', to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_role_in_game', to='player.Player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_role_in_game', to='characters.Role')),
            ],
        ),
    ]
