# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playersroleingame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersroleingame',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_role_in_game', to='player.Player'),
        ),
    ]
